services:

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter-cuda
    container_name: jupyter
    ports: 
    - "8888:8888"
    volumes:
      - ../notebooks:/home/jovyan/work/notebooks     
      - ./src:/home/jovyan/work/src        
      - /mnt/data:/home/jovyan/data        
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: always

  mlflow:
    build:
       context: . 
       dockerfile: Dockerfile.mlflow
    container_name: mlflow
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:8000 
      - MLFLOW_S3_ENDPOINT_URL=https://chi.tacc.chameleoncloud.org:7480
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}  
    volumes:
      - /mnt/metrics:/mlflow/mlruns 
    command:
      - mlflow
      - server
      - --backend-store-uri=/mlflow/mlruns
      - --artifacts-destination=s3://fancyproject-mlflow-artifacts
      - --serve-artifacts
      - --host=0.0.0.0
      - --port=8000


volumes:
  mlruns:
